### PR TITLE
Added Virtual Collection options

### PR DESCRIPTION
**Pull request by masylum**
So we can implement comparators :)

```js
    notifications_by_project = Backbone.buildGroupedCollection({
      collection: Teambox.Data.notifications
    , GroupCollection: this.getGroupedCollection()
    , vc_options: {
        comparator: function (a, b) {
          if (a.isMine() !== b.isMine()) {
            return _.compare(a.isMine(), b.isMine());
          }

          return _.compare(a.get('created_at'), b.get('created_at'));
        }
      }
    , groupBy: _.fGet('project_id')
    })
```

### CODE REVIEW

**Comment by andresgutgon** [comment]
:+1:

**Comment by p3drosola** [comment]
you can't sort at the original collection level?

**Comment by masylum** [comment]
Not sure it would work to be honest. Specially on updating fields since it won't reorder them (it will just create new groups if needed).

**Comment by p3drosola** [comment]
ok! sounds good then.

**Pull request merged**
