### PR TITLE
Added comparator capabilities to grouped collections

### PR DESCRIPTION
**Pull request by masylum**
Pretty self-explanatory

### CODE REVIEW

**Comment by andresgutgon** [comment]
Maybe spec

**Comment by masylum** [comment]
Added specs

**Comment by andresgutgon** [comment]
👍

**Comment by p3drosola** [comment]
I'm not super familiar with this code at the moment, but can't you achieve the same thing by passing in the GroupCollection constructor option? Also it's more scalable as you can set any property on the group collection, not just the comparator.

```js
Backbone.buildGroupedCollection({
  collection: animals
, GroupCollection: Backbone.Collection.extend({comparator: byClub})
, groupBy: function (animal) {
    return animal.get('color');
  }
});

**Comment by masylum** [comment]
I guess it could work that way but I've seen many times people passing `comparators` thinking they would apply so I think that's the API people expect.

**Comment by p3drosola** [comment]
hmm, dunno man. dunno. this raises existential questions... should software be written for humans or make a semblance of sense? Where do the benefits of creative constraints end, and tool-induced mental limitations set in? What's more delicious, and avocado or a pear?

**Comment by andresgutgon** [comment]
LOL

**Pull request merged**
